# Generated by Django 5.1.4 on 2024-12-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_business_alter_invoice_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
